@extends('layouts.librenmsv1') @section('title','IAPM Interface Matrix') @section('content')<div class="container-fluid">@include('iapm::partials.nav')<h2>Interface Matrix</h2>
<form class="form-inline" method="get"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Interface or description"><input class="form-control" name="device_group_id" value="{{ request('device_group_id') }}" placeholder="Device group ID"><input class="form-control" name="device_id" value="{{ request('device_id') }}" placeholder="Device ID"><input class="form-control" name="location_id" value="{{ request('location_id') }}" placeholder="Location ID"><select class="form-control" name="policy_id"><option value="">Any policy</option>@foreach($policies as $policy)<option value="{{ $policy->id }}" @selected(request('policy_id')==$policy->id)>{{ $policy->name }}</option>@endforeach</select><select class="form-control" name="assignment_source"><option value="">Any source</option>@foreach(['port','port_group','device','device_group','location','ifalias_regex','ifname_regex','interface_type','default','configured_default'] as $source)<option @selected(request('assignment_source')===$source)>{{ $source }}</option>@endforeach</select><select class="form-control" name="admin"><option value="">Any admin</option>@foreach(['up','down'] as $v)<option @selected(request('admin')===$v)>{{ $v }}</option>@endforeach</select><select class="form-control" name="oper"><option value="">Any oper</option>@foreach(['up','down'] as $v)<option @selected(request('oper')===$v)>{{ $v }}</option>@endforeach</select><select class="form-control" name="incident_state"><option value="">Any incident</option>@foreach(['pending','active','acknowledged','suppressed','recovered'] as $v)<option @selected(request('incident_state')===$v)>{{ $v }}</option>@endforeach</select>@foreach(['no_policy'=>'No policy','active_incident'=>'Open incident','muted'=>'Muted'] as $key=>$label)<label><input type="checkbox" name="{{ $key }}" value="1" @checked(request()->boolean($key))> {{ $label }}</label>@endforeach<button class="btn btn-default">Filter</button><a class="btn btn-default" href="{{ route('iapm.matrix.export',request()->query()) }}">Export CSV</a></form>
<div class="alert alert-info">Policy/source/no-policy filters use the materialized cache. Run <code>php artisan iapm:cache-rebuild</code> after broad policy or assignment changes.</div><form method="post" action="{{ route('iapm.matrix.bulk') }}">@csrf<div class="form-inline"><select class="form-control" name="operation"><option value="assign">Assign policy</option><option value="remove_assignment">Remove explicit assignment</option><option value="mute">Mute</option><option value="unmute">Unmute</option></select><select class="form-control" name="policy_id"><option value="">Choose policy</option>@foreach($policies as $policy)<option value="{{ $policy->id }}">{{ $policy->name }}</option>@endforeach</select><input type="datetime-local" class="form-control" name="muted_until"><button class="btn btn-warning" onclick="return confirm('Apply this operation to selected interfaces?')">Apply</button></div><div class="iapm-table-wrap"><table class="table table-hover table-condensed iapm-sticky"><thead><tr><th><input type="checkbox" onclick="document.querySelectorAll('.iapm-port').forEach(e=>e.checked=this.checked)"></th><th class="iapm-num">port_id</th><th>Device</th><th>Interface</th><th>Description</th><th>Location</th><th>Admin</th><th>Oper</th><th>Policy</th><th>Assignment source</th><th>Incident</th><th>Tools</th></tr></thead><tbody>
{{-- P1-1: port_id was previously only the invisible value of each row's
     checkbox, yet Simulate Alert, Policy Test and Template Preview all demand
     it. It is now shown, copyable, and wired into per-row shortcuts. --}}
@foreach($rows as $row)@php($p=$row['port'])@php($portUrl=\LibreNMS\Plugins\InterfaceAlertPolicyManager\Support\LibreNmsRoutes::port($p->device_id,$p->port_id))<tr>
<td><input class="iapm-port" type="checkbox" name="port_ids[]" value="{{ $p->port_id }}" aria-label="Select {{ $p->device->hostname }} {{ $p->ifName }}"></td>
<td class="iapm-num"><code>{{ $p->port_id }}</code> <button type="button" class="btn btn-link btn-xs" data-iapm-copy-text="{{ $p->port_id }}" title="Copy port_id {{ $p->port_id }}" aria-label="Copy port_id {{ $p->port_id }}"><i class="fa fa-copy"></i></button></td>
<td><a href="{{ \LibreNMS\Plugins\InterfaceAlertPolicyManager\Support\LibreNmsRoutes::device($p->device_id) }}">{{ $p->device->hostname }}</a></td>
<td><a href="{{ $portUrl }}" title="Open {{ $p->ifName }} in LibreNMS">{{ $p->ifName }}</a></td>
<td class="iapm-truncate" title="{{ $p->ifAlias }}">{{ $p->ifAlias }}</td>
<td>{{ $p->device->location?->location }}</td>
<td>{{ $p->ifAdminStatus?->value }}</td>
<td>{{ $p->ifOperStatus?->value }}</td>
<td>@if($row['policy'])<a href="{{ route('iapm.policies.edit',$row['policy']) }}">{{ $row['policy']->name }}</a>@else<span class="text-warning">No policy</span>@endif</td>
<td title="{{ collect($row['candidates'])->map(fn($a)=>$a->policy->name)->implode(', ') }}">@if($row['winner'])<a href="{{ route('iapm.assignments.edit',$row['winner']) }}">{{ $row['winner']->assignment_type->value }}</a>@else<span class="iapm-hint">&mdash;</span>@endif</td>
<td>@if($row['incident'])<a href="{{ route('iapm.incidents.show',$row['incident']) }}">@include('iapm::partials.state-label',['state'=>$row['incident']->state->value])</a>@endif</td>
<td class="iapm-actions" style="white-space:nowrap;">
    <a class="btn btn-default btn-xs" href="{{ route('iapm.policy-test',['port_id'=>$p->port_id]) }}" title="Policy Test for port_id {{ $p->port_id }}" aria-label="Policy Test for {{ $p->ifName }}"><i class="fa fa-flask"></i></a>
    <a class="btn btn-default btn-xs" href="{{ route('iapm.simulate',['port_id'=>$p->port_id]) }}" title="Simulate an alert for port_id {{ $p->port_id }}" aria-label="Simulate an alert for {{ $p->ifName }}"><i class="fa fa-bolt"></i></a>
    <a class="btn btn-default btn-xs" href="{{ $portUrl }}" title="Open in LibreNMS" aria-label="Open {{ $p->ifName }} in LibreNMS"><i class="fa fa-external-link"></i></a>
</td>
</tr>@endforeach</tbody></table></div></form>{{ $rows->links() }}</div>@endsection
