@extends('layouts.librenmsv1') @section('title','IAPM Incidents') @section('content')
<div class="container-fluid">@include('iapm::partials.nav')<h2>Incidents</h2>
<form class="form-inline" method="get"><select name="state" class="form-control"><option value="">All states</option>@foreach(['pending','active','acknowledged','suppressed','recovered'] as $v)<option @selected(request('state')===$v)>{{ $v }}</option>@endforeach</select><input class="form-control" name="device_id" value="{{ request('device_id') }}" placeholder="Device ID"><button class="btn btn-default">Filter</button></form>
<form method="post" action="{{ route('iapm.incidents.bulk') }}">@csrf<div class="form-inline"><select name="operation" class="form-control"><option value="acknowledge">Acknowledge</option><option value="mute">Mute</option><option value="unmute">Unmute</option></select><input type="datetime-local" name="muted_until" class="form-control"><button class="btn btn-warning" onclick="return confirm('Apply to selected incidents?')">Apply</button></div>
@if($incidents->count())
<div class="table-responsive"><table class="table table-hover"><thead><tr><th><input type="checkbox" onclick="document.querySelectorAll('.iapm-incident').forEach(e=>e.checked=this.checked)"></th><th>ID</th><th>Interface</th><th>Policy</th><th>State</th><th>Severity</th><th>Last seen</th></tr></thead><tbody>@foreach($incidents as $i)@php($c=(array)$i->context_json)<tr><td><input class="iapm-incident" type="checkbox" name="incident_ids[]" value="{{ $i->id }}"></td><td><a href="{{ route('iapm.incidents.show',$i) }}">{{ $i->id }}</a></td><td><a href="{{ route('device',$i->device_id) }}">{{ $c['hostname'] ?? $i->device_id }}</a> — {{ $c['ifName'] ?? $i->port_id }}</td><td>@if($i->policy)<a href="{{ route('iapm.policies.edit',$i->policy) }}">{{ $i->policy->name }}</a>@else<span class="text-warning">none</span>@endif</td><td>@include('iapm::partials.state-label',['state'=>$i->state->value])</td><td>{{ $i->severity->value }}</td><td style="white-space:nowrap;">{{ $i->last_seen_at }}</td></tr>@endforeach</tbody></table></div></form>{{ $incidents->links() }}
@else
</form>@include('iapm::partials.empty-state',['title'=>'No incidents match','body'=>'No interface incidents recorded yet, or none match the current filter. Incidents appear once LibreNMS posts an alert to IAPM.','route'=>route('iapm.setup-helper'),'action'=>'Open setup helper'])
@endif
</div>@endsection
