@extends('layouts.librenmsv1') @section('title','IAPM Incident '.$incident->id) @section('content')
<div class="container-fluid">@include('iapm::partials.nav')<h2>Incident {{ $incident->id }}</h2>
<dl class="dl-horizontal"><dt>Key</dt><dd>{{ $incident->incident_key }}</dd><dt>State</dt><dd>{{ $incident->state->value }}</dd><dt>Device / port</dt><dd>{{ $incident->device_id }} / {{ $incident->port_id }}</dd><dt>Policy</dt><dd>{{ $incident->policy?->name }}</dd><dt>Suppression</dt><dd>{{ $incident->suppression_reason }}</dd><dt>Muted until</dt><dd>{{ $incident->muted_until }}</dd></dl>
@if($incident->state->value!=='acknowledged'&&$incident->state->value!=='recovered')<form method="post" action="{{ route('iapm.incidents.acknowledge',$incident) }}">@csrf<button class="btn btn-primary">Acknowledge</button></form>@elseif($incident->state->value==='acknowledged')<form method="post" action="{{ route('iapm.incidents.unacknowledge',$incident) }}">@csrf<button class="btn btn-default">Unacknowledge</button></form>@endif
<form method="post" action="{{ route('iapm.incidents.reconcile',$incident) }}">@csrf<button class="btn btn-default">Reconcile</button></form>
<form class="form-inline" method="post" action="{{ route('iapm.incidents.mute',$incident) }}">@csrf<input type="datetime-local" name="muted_until" required class="form-control"><button class="btn btn-warning">Mute</button></form>@if($incident->muted_until)<form method="post" action="{{ route('iapm.incidents.unmute',$incident) }}">@csrf<button class="btn btn-default">Unmute</button></form>@endif
@if($incident->policy)<h3>Controlled resend</h3><form class="form-inline" method="post" action="{{ route('iapm.incidents.resend',$incident) }}" onsubmit="return confirm('Send this notification action now? Dry-run settings still apply.')">@csrf<select class="form-control" name="action_id">@foreach($incident->policy->actions as $action)<option value="{{ $action->id }}">{{ $action->phase->value }} — {{ $action->destination?->name }}</option>@endforeach</select><button class="btn btn-warning">Resend action</button></form>@endif
<h3>Timeline</h3><table class="table"><thead><tr><th>Time</th><th>Event</th><th>Message</th></tr></thead><tbody>@foreach($incident->events->sortByDesc('created_at') as $e)<tr><td>{{ $e->created_at }}</td><td>{{ $e->event_type }}</td><td>{{ $e->event_message }}</td></tr>@endforeach</tbody></table>
<h3>Deliveries</h3><table class="table table-condensed"><thead><tr><th>Time</th><th>Phase</th><th>Status</th><th>HTTP</th><th>Error</th></tr></thead><tbody>@foreach($incident->deliveries->sortByDesc('created_at') as $delivery)<tr><td>{{ $delivery->created_at }}</td><td>{{ $delivery->phase }}</td><td>{{ $delivery->status }}</td><td>{{ $delivery->response_status }}</td><td>{{ $delivery->error_message }}</td></tr>@endforeach</tbody></table></div>@endsection
