@extends('layouts.librenmsv1') @section('title',$policy->exists?'Edit IAPM Policy':'Create IAPM Policy') @section('content')
<div class="container-fluid">@include('iapm::partials.nav')<h2>{{ $policy->exists?'Edit':'Create' }} Policy</h2>
<p class="text-muted">Timing controls the incident lifecycle: <strong>trigger delay</strong> + <strong>failed polls</strong> must both be satisfied before an incident becomes active and notifies; <strong>repeat</strong>/<strong>maximum repeats</strong> govern reminders; <strong>recovery hold-down</strong> is how long an interface must stay up before it's marked recovered. Set 0 for immediate. Add notification <em>actions</em> below after saving.</p>
<form method="post" action="{{ $policy->exists?route('iapm.policies.update',$policy):route('iapm.policies.store') }}">@csrf @if($policy->exists)@method('PUT')@endif<div class="row"><div class="col-md-6">
@foreach(['name'=>'Name','description'=>'Description','priority'=>'Priority','default_receiver'=>'Default receiver','trigger_after_seconds'=>'Trigger delay (seconds)','failed_poll_count'=>'Failed polls','recovery_after_seconds'=>'Recovery hold-down (seconds)','repeat_seconds'=>'Repeat seconds','maximum_repeats'=>'Maximum repeats'] as $key=>$label)<div class="form-group"><label>{{ $label }}</label>@if($key==='description')<textarea class="form-control" name="{{ $key }}">{{ old($key,$policy->$key) }}</textarea>@else<input class="form-control" name="{{ $key }}" value="{{ old($key,$policy->$key) }}" {{ $key==='name'?'required':'' }}>@endif</div>@endforeach
<div class="form-group"><label>Severity</label><select class="form-control" name="severity">@foreach(['info','warning','critical'] as $v)<option @selected(old('severity',$policy->severity?->value??'critical')===$v)>{{ $v }}</option>@endforeach</select></div></div><div class="col-md-6">
@foreach(['enabled','notifications_enabled','notify_recovery','suppress_device_down','suppress_admin_down','suppress_ignored_port','suppress_disabled_port','suppress_deleted_port','suppress_maintenance','suppress_parent_down'] as $key)<input type="hidden" name="{{ $key }}" value="0"><div class="checkbox"><label><input type="checkbox" name="{{ $key }}" value="1" @checked(old($key,$policy->exists?$policy->$key:true))> {{ str_replace('_',' ',ucfirst($key)) }}</label></div>@endforeach
<input type="hidden" name="suppress_uplink_down" value="0"><div class="checkbox"><label><input type="checkbox" name="suppress_uplink_down" value="1" @checked(old('suppress_uplink_down',$policy->exists?$policy->suppress_uplink_down:false))> Suppress when uplink down <span class="help-block" style="display:inline">(root-cause: needs an uplink port group set in Settings)</span></label></div>
<div class="form-group"><label>Schedule</label><select class="form-control" name="business_schedule_id"><option value="">24/7</option>@foreach($schedules as $s)<option value="{{ $s->id }}" @selected(old('business_schedule_id',$policy->business_schedule_id)==$s->id)>{{ $s->name }}</option>@endforeach</select></div>
<fieldset style="margin-top:10px;"><legend style="font-size:14px;">Flap dampening <small class="text-muted">(optional)</small></legend>
<p class="help-block">When an interface cycles down/up faster than the threshold, send one "flapping" notice and dampen the rest until it stabilises. Leave threshold blank to disable.</p>
@foreach(['flap_threshold'=>'Flap threshold (down/up cycles)','flap_window_seconds'=>'Flap window (seconds)','flap_settle_seconds'=>'Settle period (seconds)'] as $key=>$label)<div class="form-group"><label>{{ $label }}</label><input class="form-control" name="{{ $key }}" value="{{ old($key,$policy->$key) }}"></div>@endforeach
</fieldset>
</div></div><button class="btn btn-primary">Save</button></form>
@if($policy->exists)<hr><h3>Notification actions <a class="btn btn-primary btn-sm" href="{{ route('iapm.actions.create',$policy) }}">Add action</a></h3>
<p class="text-muted">Build an <strong>escalation chain</strong> by adding multiple <em>escalation</em> actions with increasing delays and different destinations/receivers (e.g. 10m → primary, 20m → secondary, 30m → manager). Delays are measured from when the incident triggered; acknowledging the incident stops further escalation.</p><table class="table"><thead><tr><th>Phase</th><th>Destination</th><th>Delay</th><th>Repeat</th><th>Maximum</th><th>Status</th></tr></thead><tbody>@foreach($policy->actions()->with('destination')->orderBy('sort_order')->get() as $action)<tr><td><a href="{{ route('iapm.actions.edit',$action) }}">{{ $action->phase->value }}</a></td><td>{{ $action->destination?->name }}</td><td>{{ $action->delay_seconds }}</td><td>{{ $action->repeat_seconds }}</td><td>{{ $action->maximum_sends }}</td><td>{{ $action->enabled?'Enabled':'Disabled' }}</td></tr>@endforeach</tbody></table>
<form method="post" action="{{ route('iapm.policies.clone',$policy) }}">@csrf<button class="btn btn-default">Clone policy</button></form>
<form method="post" action="{{ route('iapm.policies.destroy',$policy) }}" onsubmit="return confirm('Delete this policy?')">@csrf @method('DELETE')
@if(($openIncidentCount??0)>0)<div class="form-group"><label>This policy has {{ $openIncidentCount }} active incident(s). Migrate them to</label><select name="migrate_to" class="form-control" required><option value="">Select a policy…</option>@foreach($otherPolicies as $p)<option value="{{ $p->id }}">{{ $p->name }}</option>@endforeach</select></div>@endif
<button class="btn btn-danger">Delete</button></form>@endif</div>@endsection
