<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('iapm_schedules', function (Blueprint $t): void { $t->id(); $t->string('name'); $t->string('timezone', 64); $t->boolean('enabled')->default(true); $t->json('schedule_json'); $t->timestamps(); });
        Schema::create('iapm_policies', function (Blueprint $t): void {
            $t->id(); $t->string('name')->unique(); $t->text('description')->nullable(); $t->boolean('enabled')->default(true); $t->integer('priority')->default(0); $t->string('severity', 16)->default('critical'); $t->string('default_receiver')->nullable(); $t->boolean('notifications_enabled')->default(true); $t->unsignedInteger('trigger_after_seconds')->default(0); $t->unsignedInteger('failed_poll_count')->default(1); $t->unsignedInteger('recovery_after_seconds')->default(0); $t->unsignedInteger('repeat_seconds')->nullable(); $t->unsignedInteger('maximum_repeats')->nullable(); $t->boolean('notify_recovery')->default(true); $t->boolean('suppress_device_down')->default(true); $t->boolean('suppress_admin_down')->default(true); $t->boolean('suppress_ignored_port')->default(true); $t->boolean('suppress_disabled_port')->default(true); $t->boolean('suppress_deleted_port')->default(true); $t->boolean('suppress_maintenance')->default(true); $t->boolean('suppress_parent_down')->default(true); $t->foreignId('business_schedule_id')->nullable()->constrained('iapm_schedules')->nullOnDelete(); $t->unsignedBigInteger('created_by')->nullable(); $t->unsignedBigInteger('updated_by')->nullable(); $t->timestamps(); $t->index(['enabled', 'priority']);
        });
        Schema::create('iapm_assignments', function (Blueprint $t): void {
            $t->id(); $t->foreignId('policy_id')->constrained('iapm_policies')->cascadeOnDelete(); $t->string('assignment_type', 32); $t->string('assignment_reference')->nullable(); $t->text('match_expression')->nullable(); $t->string('match_mode', 16)->default('any'); $t->integer('priority')->default(0); $t->boolean('enabled')->default(true); $t->json('metadata_json')->nullable(); $t->timestamps(); $t->index(['assignment_type', 'assignment_reference', 'enabled'], 'iapm_assignment_lookup'); $t->index(['assignment_type', 'priority']);
        });
        Schema::create('iapm_assignment_device_groups', function (Blueprint $t): void { $t->foreignId('assignment_id')->constrained('iapm_assignments')->cascadeOnDelete(); $t->unsignedBigInteger('device_group_id'); $t->string('inclusion_mode', 16)->default('include'); $t->primary(['assignment_id', 'device_group_id']); $t->index('device_group_id'); });
        Schema::create('iapm_destinations', function (Blueprint $t): void { $t->id(); $t->string('name')->unique(); $t->string('type', 32); $t->boolean('enabled')->default(true); $t->text('configuration_encrypted'); $t->timestamps(); $t->index(['type', 'enabled']); });
        Schema::create('iapm_policy_actions', function (Blueprint $t): void { $t->id(); $t->foreignId('policy_id')->constrained('iapm_policies')->cascadeOnDelete(); $t->foreignId('destination_id')->constrained('iapm_destinations')->restrictOnDelete(); $t->string('phase', 24); $t->unsignedInteger('delay_seconds')->default(0); $t->unsignedInteger('repeat_seconds')->nullable(); $t->unsignedInteger('maximum_sends')->nullable(); $t->json('receivers_json')->nullable(); $t->text('message_template')->nullable(); $t->boolean('enabled')->default(true); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); $t->index(['phase', 'enabled']); });
        Schema::create('iapm_incidents', function (Blueprint $t): void {
            $t->id(); $t->string('incident_key')->unique(); $t->unsignedBigInteger('source_alert_id')->nullable(); $t->string('source_alert_uid')->nullable(); $t->unsignedBigInteger('source_rule_id')->nullable(); $t->unsignedBigInteger('device_id'); $t->unsignedBigInteger('port_id'); $t->foreignId('policy_id')->nullable()->constrained('iapm_policies')->nullOnDelete(); $t->string('state', 20); $t->string('severity', 16); $t->dateTime('first_seen_at'); $t->dateTime('triggered_at')->nullable(); $t->dateTime('last_seen_at'); $t->dateTime('recovered_at')->nullable(); $t->dateTime('acknowledged_at')->nullable(); $t->unsignedBigInteger('acknowledged_by')->nullable(); $t->dateTime('muted_until')->nullable(); $t->unsignedInteger('notification_count')->default(0); $t->dateTime('last_notification_at')->nullable(); $t->string('suppression_reason')->nullable(); $t->json('context_json'); $t->timestamps(); $t->index(['state', 'last_seen_at']); $t->index(['device_id', 'port_id', 'state']); $t->index(['source_alert_id', 'state']); $t->index(['policy_id', 'state']);
        });
        Schema::create('iapm_incident_events', function (Blueprint $t): void { $t->id(); $t->foreignId('incident_id')->constrained('iapm_incidents')->cascadeOnDelete(); $t->string('event_type', 32); $t->text('event_message'); $t->json('event_data')->nullable(); $t->unsignedBigInteger('actor_user_id')->nullable(); $t->timestamps(); $t->index(['incident_id', 'created_at']); $t->index(['event_type', 'created_at']); });
        Schema::create('iapm_delivery_logs', function (Blueprint $t): void { $t->id(); $t->foreignId('incident_id')->nullable()->constrained('iapm_incidents')->cascadeOnDelete(); $t->foreignId('destination_id')->constrained('iapm_destinations')->restrictOnDelete(); $t->foreignId('policy_action_id')->nullable()->constrained('iapm_policy_actions')->nullOnDelete(); $t->string('phase', 24); $t->unsignedInteger('attempt')->default(1); $t->string('status', 24); $t->text('request_url')->nullable(); $t->text('request_payload_redacted')->nullable(); $t->unsignedSmallInteger('response_status')->nullable(); $t->text('response_body_redacted')->nullable(); $t->text('error_message')->nullable(); $t->dateTime('sent_at')->nullable(); $t->timestamps(); $t->index(['status', 'created_at']); $t->index(['incident_id', 'phase']); });
        Schema::create('iapm_settings', function (Blueprint $t): void { $t->string('setting_key')->primary(); $t->text('setting_value'); $t->dateTime('updated_at')->nullable(); });
        Schema::create('iapm_interface_policy_cache', function (Blueprint $t): void { $t->unsignedBigInteger('port_id')->primary(); $t->unsignedBigInteger('policy_id')->nullable(); $t->unsignedBigInteger('assignment_id')->nullable(); $t->string('assignment_source', 32)->nullable(); $t->json('candidate_assignment_ids')->nullable(); $t->dateTime('resolved_at'); $t->index(['policy_id', 'port_id']); $t->index(['assignment_source', 'port_id']); });
        Schema::create('iapm_audit_logs', function (Blueprint $t): void { $t->id(); $t->unsignedBigInteger('user_id')->nullable(); $t->string('action', 48); $t->string('object_type', 64); $t->unsignedBigInteger('object_id')->nullable(); $t->json('before_data')->nullable(); $t->json('after_data')->nullable(); $t->string('source_ip', 45)->nullable(); $t->dateTime('created_at'); $t->index(['object_type', 'object_id']); $t->index('created_at'); });
    }

    public function down(): void
    {
        foreach (['iapm_audit_logs', 'iapm_interface_policy_cache', 'iapm_settings', 'iapm_delivery_logs', 'iapm_incident_events', 'iapm_incidents', 'iapm_policy_actions', 'iapm_destinations', 'iapm_assignment_device_groups', 'iapm_assignments', 'iapm_policies', 'iapm_schedules'] as $table) Schema::dropIfExists($table);
    }
};
